### ISSUE TITLE
Destination dist/libs/libs.js not written because src files were empty.

### ISSUE THREAD

**Issue by rekosko** [micromata/generator-bootstrap-kickstart#33] opened 2015-11-23 23:59 UTC
Hello,

using `grunt build` I'm getting the following error:

    Running "uglify:bower" (uglify) task
    >> Destination dist/libs/libs.js not written because src files were empty.
    >> No files created.

I've just noticed that after I wanted to share some of my work to others.

I'm working on version 

    npm list -g | grep generator-bootstrap-kickstart
    ├─┬ generator-bootstrap-kickstart@1.2.4

`1.2.4` of generator-bootstrap-kickstart.

In html I use:

    
    ...
    

My `Gruntfile.js` is one folder up in hierarchy, I've set up the new base for it using `grunt.file.setBase('./wwwroot');`

Everything is working beside this one error... I believe there's a problem with some paths but I'm rather rookie in this and I don't have any idea how I should fix this issue...

I saw there's new version of bootstrap-kickstart but I'm not too sure if I can upgrade my current version without any issues so lets say I want to stay on this `1.2.4`.

Some help would be appreciated.

**Comment by mischah** [comment] 2015-11-24 08:42
Hej @rekosko,

thanks for the detailed report. I'll try to reproduce this soon.

**Comment by rekosko** [comment] 2015-11-24 09:46
@mischah thanks for you reply:) I hope that you can help me. As far as I know I didn't change any lines of code regarding this libs.js so you should be able to reproduce this issue - in fact I didn't change anything in my `Gruntfile.js` except moving it out of the working directory and setting new `cwd`. Every `less` file and other things are building correctly so I would assume that there's some mistake in `Gruntfile.js` you've provided with this `1.2.4` build.

Hope to hear from you soon.

**Comment by rekosko** [comment] 2015-11-24 20:10
I've updated to newest version of `generator-bootstrap-kickstart` but still getting the same message... I guess I need to correct my paths but I don't know where in the `Gruntfile.js` giving that as I said I've moved it one folder up and changed the `cwd` for grunt.

**Comment by mischah** [comment] 2015-11-24 21:26
mhm. cant reproduce it right know. I got tons of other issues when moving the gruntfile up one directory level.

Did you meant it that way?
```
.
├── .gitignore
├── Gruntfile.js
└── www_root
    ├── .DS_Store
    ├── .bowerrc
    ├── .editorconfig
    ├── .eslintrc
    ├── .jshintrc
    ├── .postinstall.js
    ├── CHANGELOG.md
    ├── CONTRIBUTING.md
    ├── LICENSE
    ├── README.md
    ├── assets
    ├── bower.json
    ├── demoElements.hbs
    ├── dist
    ├── docs
    ├── humans.txt
    ├── index.hbs
    ├── libs
    ├── package.json
    ├── partials
    ├── reports
    ├── server
    ├── stickyFooter.hbs
    └── templates
```

I don’t see a reason for doing that. You could leave it by the default directory structure and rename the `dist` directory to `wwwroot` within the gruntfile:

```javascript
// Configurable paths
config: {
  dist: 'wwwroot',
  reports: 'reports',
  docs: 'docs',
  server: 'server'
},
```

Or do you have another usecase for doing that wwwrot thing?

To further investigate what causes the error in your case I could need the verbose output of grunt.
You could provide that by entering `grunt build --verbose`.

**Comment by rekosko** [comment] 2015-11-24 21:59
I will probably restructure my solution - I'm using this framework in my ASP.NET (Umbraco CMS) solution. I intented to put `Gruntfile.js`, `libs` and `node_modules` and some `bower` files in root of my web project but it looks like it's causing me a little problems:)... the grunt ouput was that src files for libs were missing so it has to be some problems with paths. A little bit shame that I couldn't do what I wanted but well...

**Comment by mischah** [comment] 2015-11-24 22:07
I’m closing this for now. Feel free to reopen or open another issue in case you need too :blush:

**Closed by mischah** 2015-11-24 22:07 UTC
